name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  carousel_slider: ^5.1.1
  auto_size_text: ^3.0.0
  google_fonts: ^6.3.3
  flutter_secure_storage: ^9.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
